export const colors = {
  // Base Colors
  blue: {
    50: 'var(--color-blue-50)',
    100: 'var(--color-blue-100)',
    200: 'var(--color-blue-200)',
    300: 'var(--color-blue-300)',
    400: 'var(--color-blue-400)',
    500: 'var(--color-blue-500)',
    600: 'var(--color-blue-600)',
    700: 'var(--color-blue-700)',
    800: 'var(--color-blue-800)',
    900: 'var(--color-blue-900)',
    10: 'var(--color-blue-10)',
  },
  green: {
    50: 'var(--color-green-50)',
    100: 'var(--color-green-100)',
    200: 'var(--color-green-200)',
    300: 'var(--color-green-300)',
    400: 'var(--color-green-400)',
    500: 'var(--color-green-500)',
    600: 'var(--color-green-600)',
    700: 'var(--color-green-700)',
    800: 'var(--color-green-800)',
    900: 'var(--color-green-900)',
  },
  night: {
    50: 'var(--color-night-50)',
    100: 'var(--color-night-100)',
    200: 'var(--color-night-200)',
    300: 'var(--color-night-300)',
    400: 'var(--color-night-400)',
    500: 'var(--color-night-500)',
    600: 'var(--color-night-600)',
    700: 'var(--color-night-700)',
    800: 'var(--color-night-800)',
    900: 'var(--color-night-900)',
  },
  gray: {
    50: 'var(--color-gray-50)',
    100: 'var(--color-gray-100)',
    200: 'var(--color-gray-200)',
    300: 'var(--color-gray-300)',
    400: 'var(--color-gray-400)',
    500: 'var(--color-gray-500)',
    600: 'var(--color-gray-600)',
    700: 'var(--color-gray-700)',
    800: 'var(--color-gray-800)',
    900: 'var(--color-gray-900)',
    white: 'var(--color-gray-white)',
  },
  red: {
    50: 'var(--color-red-50)',
    100: 'var(--color-red-100)',
    200: 'var(--color-red-200)',
    300: 'var(--color-red-300)',
    400: 'var(--color-red-400)',
    500: 'var(--color-red-500)',
    600: 'var(--color-red-600)',
    700: 'var(--color-red-700)',
    800: 'var(--color-red-800)',
    900: 'var(--color-red-900)',
  },
  orange: {
    50: 'var(--color-orange-50)',
    100: 'var(--color-orange-100)',
    200: 'var(--color-orange-200)',
    300: 'var(--color-orange-300)',
    400: 'var(--color-orange-400)',
    500: 'var(--color-orange-500)',
    600: 'var(--color-orange-600)',
    700: 'var(--color-orange-700)',
    800: 'var(--color-orange-800)',
    900: 'var(--color-orange-900)',
  },
  yellow: {
    50: 'var(--color-yellow-50)',
    100: 'var(--color-yellow-100)',
    200: 'var(--color-yellow-200)',
    300: 'var(--color-yellow-300)',
    400: 'var(--color-yellow-400)',
    500: 'var(--color-yellow-500)',
    600: 'var(--color-yellow-600)',
    700: 'var(--color-yellow-700)',
    800: 'var(--color-yellow-800)',
    900: 'var(--color-yellow-900)',
  },
  purple: {
    50: 'var(--color-purple-50)',
    100: 'var(--color-purple-100)',
    200: 'var(--color-purple-200)',
    300: 'var(--color-purple-300)',
    400: 'var(--color-purple-400)',
    500: 'var(--color-purple-500)',
    600: 'var(--color-purple-600)',
    700: 'var(--color-purple-700)',
    800: 'var(--color-purple-800)',
    900: 'var(--color-purple-900)',
  },

  // Semantic Palettes
  primary: {
    50: 'var(--primary-50)',
    100: 'var(--primary-100)',
    200: 'var(--primary-200)',
    300: 'var(--primary-300)',
    400: 'var(--primary-400)',
    500: 'var(--primary-500)',
    600: 'var(--primary-600)',
    700: 'var(--primary-700)',
    800: 'var(--primary-800)',
    900: 'var(--primary-900)',
  },
  success: {
    50: 'var(--success-50)',
    100: 'var(--success-100)',
    200: 'var(--success-200)',
    300: 'var(--success-300)',
    400: 'var(--success-400)',
    500: 'var(--success-500)',
    600: 'var(--success-600)',
    700: 'var(--success-700)',
    800: 'var(--success-800)',
    900: 'var(--success-900)',
  },
  secondary: {
    50: 'var(--secondary-50)',
    100: 'var(--secondary-100)',
    200: 'var(--secondary-200)',
    300: 'var(--secondary-300)',
    400: 'var(--secondary-400)',
    500: 'var(--secondary-500)',
    600: 'var(--secondary-600)',
    700: 'var(--secondary-700)',
    800: 'var(--secondary-800)',
    900: 'var(--secondary-900)',
  },
  neutral: {
    50: 'var(--neutral-50)',
    100: 'var(--neutral-100)',
    200: 'var(--neutral-200)',
    300: 'var(--neutral-300)',
    400: 'var(--neutral-400)',
    500: 'var(--neutral-500)',
    600: 'var(--neutral-600)',
    700: 'var(--neutral-700)',
    800: 'var(--neutral-800)',
    900: 'var(--neutral-900)',
    1000: 'var(--neutral-1000)',
  },
  warning: {
    50: 'var(--warning-50)',
    100: 'var(--warning-100)',
    200: 'var(--warning-200)',
    300: 'var(--warning-300)',
    400: 'var(--warning-400)',
    500: 'var(--warning-500)',
    600: 'var(--warning-600)',
    700: 'var(--warning-700)',
    800: 'var(--warning-800)',
    900: 'var(--warning-900)',
  },
  error: {
    50: 'var(--error-50)',
    100: 'var(--error-100)',
    200: 'var(--error-200)',
    300: 'var(--error-300)',
    400: 'var(--error-400)',
    500: 'var(--error-500)',
    600: 'var(--error-600)',
    700: 'var(--error-700)',
    800: 'var(--error-800)',
    900: 'var(--error-900)',
  },

  // Component Tokens
text: {
    'heading': 'var(--text-heading)',
    'heading off': 'var(--text-heading-off)',
    'body': 'var(--text-body)',
    'default': 'var(--text-default)',
    'action': 'var(--text-action)',
    'action-hover': 'var(--text-action-hover)',
    'blue light': 'var(--text-blue-light)',
    'blue light 2': 'var(--text-blue-light-2)',
    'blue light 3': 'var(--text-blue-light-3)',
    'disabled': 'var(--text-disabled)',
    'placeholder': {
      '2': 'var(--text-placeholder-2)',
      DEFAULT: 'var(--text-placeholder)',
    },
    'information': 'var(--text-information)',
    'error light 5': 'var(--text-error-light-5)',
    'error light 4': 'var(--text-error-light-4)',
    'error light 3': 'var(--text-error-light-3)',
    'error light 2': 'var(--text-error-light-2)',
    'error light': 'var(--text-error-light)',
    'error': 'var(--text-error)',
    'error dk': 'var(--text-error-dk)',
    'error dk 2': 'var(--text-error-dk-2)',
    'error dk 3': 'var(--text-error-dk-3)',
    'error dk 4': 'var(--text-error-dk-4)',
    'sucsess': 'var(--text-sucsess)',
    'green': 'var(--text-green)',
    'green light': 'var(--text-green-light)',
    'green light 2': 'var(--text-green-light-2)',
    'green light 3': 'var(--text-green-light-3)',
    'green light 4': 'var(--text-green-light-4)',
    'warning': 'var(--text-warning)',
    'on-action': 'var(--text-on-action)',
    'night light 4': 'var(--text-night-light-4)',
    'night light 3': 'var(--text-night-light-3)',
    'night light 2': 'var(--text-night-light-2)',
    'night light 1': 'var(--text-night-light-1)',
    'night': {
      '2': 'var(--text-night-2)',
      '3': 'var(--text-night-3)',
      '4': 'var(--text-night-4)',
      '5': 'var(--text-night-5)',
      DEFAULT: 'var(--text-night)',
    },
    'purple light 5': 'var(--text-purple-light-5)',
    'purple light 4': 'var(--text-purple-light-4)',
    'purple light 3': 'var(--text-purple-light-3)',
    'purple light 2': 'var(--text-purple-light-2)',
    'purple light 1': 'var(--text-purple-light-1)',
    'purple': 'var(--text-purple)',
    'purple dk 1': 'var(--text-purple-dk-1)',
    'purple dk 2': 'var(--text-purple-dk-2)',
    'purple dk 3': 'var(--text-purple-dk-3)',
    'purple dk 4': 'var(--text-purple-dk-4)',
    'yelow light 5': 'var(--text-yelow-light-5)',
    'yelow light 4': 'var(--text-yelow-light-4)',
    'yelow light 3': 'var(--text-yelow-light-3)',
    'yelow light 2': 'var(--text-yelow-light-2)',
    'yelow light 1': 'var(--text-yelow-light-1)',
    'yelow': 'var(--text-yelow)',
    'yelow dk 1': 'var(--text-yelow-dk-1)',
    'yelow dk 2': 'var(--text-yelow-dk-2)',
    'yelow dk 3': 'var(--text-yelow-dk-3)',
    'yelow dk 4': 'var(--text-yelow-dk-4)',
  },
  icon: {
    'default': 'var(--icon-default)',
    'action': 'var(--icon-action)',
    'action-hover': 'var(--icon-action-hover)',
    'blue light': 'var(--icon-blue-light)',
    'blue light 2': 'var(--icon-blue-light-2)',
    'blue light 3': 'var(--icon-blue-light-3)',
    'disabled': 'var(--icon-disabled)',
    'information': {
      '2': 'var(--icon-information-2)',
      DEFAULT: 'var(--icon-information)',
    },
    'error light 5': 'var(--icon-error-light-5)',
    'error light 4': 'var(--icon-error-light-4)',
    'error light 3': 'var(--icon-error-light-3)',
    'error light 2': 'var(--icon-error-light-2)',
    'error light': 'var(--icon-error-light)',
    'error': 'var(--icon-error)',
    'error dk': 'var(--icon-error-dk)',
    'error dk 2': 'var(--icon-error-dk-2)',
    'error dk 3': 'var(--icon-error-dk-3)',
    'error dk 4': 'var(--icon-error-dk-4)',
    'warning light': 'var(--icon-warning-light)',
    'sucsess': 'var(--icon-sucsess)',
    'green': 'var(--icon-green)',
    'green light': 'var(--icon-green-light)',
    'green light 2': 'var(--icon-green-light-2)',
    'green light 3': 'var(--icon-green-light-3)',
    'green light 4': 'var(--icon-green-light-4)',
    'warning': 'var(--icon-warning)',
    'on-action': 'var(--icon-on-action)',
    'placeholder': 'var(--icon-placeholder)',
    'night light 4': 'var(--icon-night-light-4)',
    'night light 3': 'var(--icon-night-light-3)',
    'night light 2': 'var(--icon-night-light-2)',
    'night light 1': 'var(--icon-night-light-1)',
    'night': {
      '2': 'var(--icon-night-2)',
      '3': 'var(--icon-night-3)',
      '4': 'var(--icon-night-4)',
      '5': 'var(--icon-night-5)',
      DEFAULT: 'var(--icon-night)',
    },
    'purple light 5': 'var(--icon-purple-light-5)',
    'purple light 4': 'var(--icon-purple-light-4)',
    'purple light 3': 'var(--icon-purple-light-3)',
    'purple light 2': 'var(--icon-purple-light-2)',
    'purple light 1': 'var(--icon-purple-light-1)',
    'purple': 'var(--icon-purple)',
    'purple dk 1': 'var(--icon-purple-dk-1)',
    'purple dk 2': 'var(--icon-purple-dk-2)',
    'purple dk 3': 'var(--icon-purple-dk-3)',
    'purple dk 4': 'var(--icon-purple-dk-4)',
    'yelow light 5': 'var(--icon-yelow-light-5)',
    'yelow light 4': 'var(--icon-yelow-light-4)',
    'yelow light 3': 'var(--icon-yelow-light-3)',
    'yelow light 2': 'var(--icon-yelow-light-2)',
    'yelow light 1': 'var(--icon-yelow-light-1)',
    'yelow': 'var(--icon-yelow)',
    'yelow dk 1': 'var(--icon-yelow-dk-1)',
    'yelow dk 2': 'var(--icon-yelow-dk-2)',
    'yelow dk 3': 'var(--icon-yelow-dk-3)',
    'yelow dk 4': 'var(--icon-yelow-dk-4)',
  },
  surface: {
    'page': 'var(--surface-page)',
    'default': 'var(--surface-default)',
    'action': 'var(--surface-action)',
    'action-hover': 'var(--surface-action-hover)',
    'blue light': 'var(--surface-blue-light)',
    'blue light 2': 'var(--surface-blue-light-2)',
    'blue light 3': 'var(--surface-blue-light-3)',
    'blue light 4': 'var(--surface-blue-light-4)',
    'sucsess': 'var(--surface-sucsess)',
    'green': 'var(--surface-green)',
    'green light': 'var(--surface-green-light)',
    'green light 2': 'var(--surface-green-light-2)',
    'green light 3': 'var(--surface-green-light-3)',
    'green light 4': 'var(--surface-green-light-4)',
    'green light 5': 'var(--surface-green-light-5)',
    'warning light': 'var(--surface-warning-light)',
    'warning': 'var(--surface-warning)',
    'error light 5': 'var(--surface-error-light-5)',
    'error light 4': 'var(--surface-error-light-4)',
    'error light 3': 'var(--surface-error-light-3)',
    'error light 2': 'var(--surface-error-light-2)',
    'error light': 'var(--surface-error-light)',
    'error': 'var(--surface-error)',
    'error dk': 'var(--surface-error-dk)',
    'error dk 2': 'var(--surface-error-dk-2)',
    'error dk 3': 'var(--surface-error-dk-3)',
    'error dk 4': 'var(--surface-error-dk-4)',
    'information': 'var(--surface-information)',
    'disabled': {
      '2': 'var(--surface-disabled-2)',
      DEFAULT: 'var(--surface-disabled)',
    },
    'black': 'var(--surface-black)',
    'night light 5': 'var(--surface-night-light-5)',
    'night light 4': 'var(--surface-night-light-4)',
    'night light 3': 'var(--surface-night-light-3)',
    'night light 2': 'var(--surface-night-light-2)',
    'night light 1': 'var(--surface-night-light-1)',
    'night': {
      '2': 'var(--surface-night-2)',
      '3': 'var(--surface-night-3)',
      '4': 'var(--surface-night-4)',
      '5': 'var(--surface-night-5)',
      DEFAULT: 'var(--surface-night)',
    },
    'light-bg': 'var(--surface-light-bg)',
    'purple light 5': 'var(--surface-purple-light-5)',
    'purple light 4': 'var(--surface-purple-light-4)',
    'purple light 3': 'var(--surface-purple-light-3)',
    'purple light 2': 'var(--surface-purple-light-2)',
    'purple light 1': 'var(--surface-purple-light-1)',
    'purple': 'var(--surface-purple)',
    'purple dk 1': 'var(--surface-purple-dk-1)',
    'purple dk 2': 'var(--surface-purple-dk-2)',
    'purple dk 3': 'var(--surface-purple-dk-3)',
    'purple dk 4': 'var(--surface-purple-dk-4)',
  },
    border: {
    default: 'var(--border-default)',
    disabled: {
      DEFAULT: 'var(--border-disabled)',
      dark: 'var(--border-disabled-dark)',
    },
    warning: {
      DEFAULT: 'var(--border-warning)',
      light: 'var(--border-warning-light)',
    },
    information: 'var(--border-information)',
    success: 'var(--border-success)',
    action: {
      DEFAULT: 'var(--border-action)',
      hover: 'var(--border-action-hover)',
    },
    focus: 'var(--border-focus)',
    black: 'var(--border-black)',
    error: 'var(--border-error)',
  },
} as const;
